all:
	g++ Employee.cpp -c
	g++ SalariedEmployee.cpp -c
	g++ CommissionEmployee.cpp -c
	g++ HourlyEmployee.cpp -c
	g++ payroll.cpp -c
	g++ reading.cpp -c
	g++ Employee.o SalariedEmployee.o CommissionEmployee.o HourlyEmployee.o payroll.o reading.o

clean:
	rm Employee.o
	rm SalariedEmployee.o
	rm HourlyEmployee.o
	rm CommissionEmployee.o
	rm reading.o
	rm payroll.o
	rm a.out
